// Minimal env injector for frontend runtime.
// Reads CHATBOT_URL from process.env or a nearby .env file and writes src/assets/env.js
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

function parseDotEnv(text) {
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const val = trimmed.slice(eq + 1).trim();
    out[key] = val;
  }
  return out;
}

function readEnvValue() {
  if (process.env.CHATBOT_URL) return process.env.CHATBOT_URL;
  const candidates = [
    join(__dirname, '../../.env'),      // when running from frontend/erp-ui/scripts
    join(__dirname, '../../../.env'),   // fallback one level higher
    join(process.cwd(), '.env')
  ];
  for (const p of candidates) {
    try {
      if (existsSync(p)) {
        const txt = readFileSync(p, 'utf8');
        const env = parseDotEnv(txt);
        if (env.CHATBOT_URL) return env.CHATBOT_URL;
      }
    } catch { /* ignore */ }
  }
  return '';
}

const value = readEnvValue();
const outDir = join(__dirname, '../src/assets');
try { mkdirSync(outDir, { recursive: true }); } catch {}
const outFile = join(outDir, 'env.js');
const js = `// Generated by scripts/inject-env.mjs\n(function(){\n  window.__ENV__ = window.__ENV__ || {};\n  window.__ENV__.CHATBOT_URL = ${JSON.stringify(value)};\n})();\n`;
writeFileSync(outFile, js, 'utf8');
console.log('Wrote', outFile, 'with CHATBOT_URL =', value ? '[set]' : '[empty]');
